package com.shadowself.training.data

import com.shadowself.data.repository.SensorDataRepository
import com.shadowself.features.FeatureExtractionPipeline
import com.shadowself.util.Logger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * TrainingDataset
 *
 * Assembles labelled float arrays for on-device model training.
 *
 * This is a one-class classification problem: we have positive samples
 * (confirmed owner behaviour) but no real negative samples at install time.
 *
 * Strategy:
 *   Positives  — feature vectors extracted from 7 days of owner usage.
 *                Label = 1.0f.
 *   Negatives  — synthetic "impostor" vectors generated by SyntheticNegativeGenerator.
 *                Label = 0.0f.
 *
 * After first deploy, any windows flagged by the owner as TRUE POSITIVES
 * (actual intrusion events) become real negative samples and are mixed into
 * future retraining rounds, gradually replacing synthetics.
 *
 * Dataset shape:
 *   features: FloatArray[n_samples][FEATURE_VECTOR_SIZE]   (64 floats per sample)
 *   labels:   FloatArray[n_samples]                        (1.0 = owner, 0.0 = impostor)
 */
@Singleton
class TrainingDataset @Inject constructor(
    private val repository: SensorDataRepository,
    private val negativeGenerator: SyntheticNegativeGenerator
) {
    companion object {
        const val FEATURE_SIZE         = FeatureExtractionPipeline.FEATURE_VECTOR_SIZE
        const val MIN_POSITIVE_SAMPLES = 100     // Need at least 100 positive windows
        const val NEGATIVE_RATIO       = 1.5f    // 1.5× as many negatives as positives
        private const val TAG          = "TrainingDataset"
    }

    data class Dataset(
        val features:       Array<FloatArray>,  // [n_samples][64]
        val labels:         FloatArray,          // [n_samples]
        val positivesCount: Int,
        val negativesCount: Int,
        val sourceDays:     Int
    ) {
        val totalSamples: Int get() = features.size

        override fun equals(other: Any?) = false   // Large arrays — skip equals
        override fun hashCode() = System.identityHashCode(this)
    }

    /**
     * Builds the full labelled dataset from stored sensor windows.
     * Runs on Dispatchers.IO — never call from main thread.
     */
    suspend fun build(sourceDays: Int = 7): Result<Dataset> = withContext(Dispatchers.IO) {
        runCatching {
            // 1. Pull raw windows from Room DB
            val windows = repository.getTrainingData(sourceDays)
            Logger.d(TAG, "Loaded ${windows.size} raw windows from last $sourceDays days")

            if (windows.size < MIN_POSITIVE_SAMPLES) {
                error("Insufficient data: ${windows.size} windows < $MIN_POSITIVE_SAMPLES minimum. " +
                      "Keep using the phone normally for a few more days.")
            }

            // 2. Extract feature vectors for positive (owner) samples
            val extractor = FeatureVectorExtractor()
            val positives = windows
                .filter { it.hasMinimumData }
                .mapNotNull { extractor.extractOrNull(it) }
                .also { Logger.d(TAG, "${it.size} valid positive vectors extracted") }

            if (positives.size < MIN_POSITIVE_SAMPLES) {
                error("Only ${positives.size} valid feature vectors — need $MIN_POSITIVE_SAMPLES. " +
                      "Many windows lacked sufficient sensor data.")
            }

            // 3. Generate synthetic negatives based on owner's distribution
            val negativeCount = (positives.size * NEGATIVE_RATIO).toInt()
            val negatives = negativeGenerator.generate(positives, negativeCount)
            Logger.d(TAG, "Generated $negativeCount synthetic negative samples")

            // 4. Merge + shuffle
            val allFeatures = (positives + negatives).toTypedArray()
            val allLabels   = FloatArray(allFeatures.size).also { labels ->
                positives.indices.forEach  { labels[it] = 1.0f }
                negatives.indices.forEach  { labels[positives.size + it] = 0.0f }
            }

            val (shuffledFeatures, shuffledLabels) = shuffleInSync(allFeatures, allLabels)

            Logger.d(TAG, "Dataset ready: ${positives.size} positives + ${negatives.size} negatives")

            Dataset(
                features       = shuffledFeatures,
                labels         = shuffledLabels,
                positivesCount = positives.size,
                negativesCount = negatives.size,
                sourceDays     = sourceDays
            )
        }
    }

    /**
     * Shuffles features and labels in lockstep so labels stay aligned.
     * Uses Fisher-Yates for a proper uniform shuffle.
     */
    private fun shuffleInSync(
        features: Array<FloatArray>,
        labels:   FloatArray
    ): Pair<Array<FloatArray>, FloatArray> {
        val n    = features.size
        val rng  = java.util.Random()
        for (i in n - 1 downTo 1) {
            val j = rng.nextInt(i + 1)
            val tmpF = features[i]; features[i] = features[j]; features[j] = tmpF
            val tmpL = labels[i];   labels[i]   = labels[j];   labels[j]   = tmpL
        }
        return Pair(features, labels)
    }
}
